### ISSUE TITLE
Create an app Color Scehme

### ISSUE THREAD

**Issue by motosharpley** [TheDevPath/googleMaps-offline-navigator#10]
Create an example color scheme document with example swatches, hex codes, and target usage.
Color schemes should take color theory into consideration. You can check out http://paletton.com for inspiration.
 ie. 
- Primary -insert rgb hex code here ie. #3c3c3c

- Primary light

- Primary dark

- Accent 1

- Accent 2

- Typography light

- Typography dark

**Comment by benreckas** [comment]
It's late now, but I can knock this out tomorrow if you want to assign it to me. I'll try to do a couple variations and maybe we can vote on the favorite as a community.

**Comment by motosharpley** [comment]
You can also reach out to @jp853 on this as he is getting started on some graphic mock ups and @pjdmatts  as he is working on the wire frames and app story board to coordinate.

**Comment by benreckas** [comment]
I created a pull request with some initial color schemes feel free to give me feedback if you want me to tweak anything.

**Comment by benreckas** [comment]
Color scheme has been merged. I believe we can close this issue.
