### ISSUE TITLE
Add protected routes for the sign-in and other pages

### ISSUE THREAD

**Issue by redragonx** [TheDevPath/googleMaps-offline-navigator#104]
We need a way to protect routes once signing on works. This is so we can show relevant pages to the user.

What is the expected behavior?
Hides sections in the navbar and deny access.

What is the current behavior?
Nothing happens.

#86 depends on this issue.

https://medium.com/the-many/adding-login-and-authentication-sections-to-your-react-or-react-native-app-7767fd251bd1

**Comment by jkwening** [comment]
@redragonx It sounds like this can be facilitated by exposing 'verifyToken' logic as an api endpoint for the front end. Front end will check whether user has an access token, if so, send a request to '/user/verify' endpoint to validate for token and route accordingly. If no token is currently cached, then user needs to sign-in/register before being granted access to protected route. Thoughts?

**Comment by motosharpley** [comment]
I think there are two pieces to what you are trying to do - client side logic/validation to check if there is or is not a user object present then for example don't show login - do show log out & profile links etc.
Then there is the secondary step for Items like user settings / account info etc. which also require server side validation. 
The client side logic prevents displaying the navigation/content but would not prevent a user from manually entering the correct url to access a protected route and that is were the server side validation steps in. 
And in the case of highly sensitive data, of which we really don't have but if we did those routes could be configured to force login regardless of a valid tokens presence or not

**Comment by motosharpley** [comment]
In addition here is the preact router for reference on things like redirects & if we need additional functionality we can always swap out for the react-router https://github.com/developit/preact-router

**Comment by jkwening** [comment]
Currently can't access "secure" end points unless signed in.
