### ISSUE TITLE
Wire frames

### ISSUE THREAD

**Issue by motosharpley** [TheDevPath/googleMaps-offline-navigator#11]
Create a set of wire frames to facilitate smooth flow through the proposed project features. See current readme file for an outline of the current use case / features list.

**Comment by motosharpley** [comment]
Builders Choice! Thanks I will assign you now.

**Comment by pjdmatts** [comment]
I had a first pass at this to go with the story boards: https://balsamiq.cloud/supkb/pc5l4

**Comment by motosharpley** [comment]
closing this issue for now. We can continue to iterate on team discussion boards.
