### ISSUE TITLE
Beginner Special - Move preact-jsx-chai 

### ISSUE THREAD

**Issue by motosharpley** [TheDevPath/googleMaps-offline-navigator#112]
In the client>package.json file move the preact-jsx-chai module from dependencies to devDependencies.
This is a starter issue for a first time user to learn the pull request process. 
Thanks for playing!

**Comment by Minh-B-Dang** [comment]
I'd like to help with this issue.

**Comment by motosharpley** [comment]
sure I will assign to you now.

**Comment by motosharpley** [comment]
I need you to accept the team invite and then I can assign to you. 
Thanks!

**Comment by Minh-B-Dang** [comment]
Oh I'm sorry I never noticed the invitation via email. I accepted the invite. I'm still very new to Github so i'm a little lost on how to proceed.

**Comment by motosharpley** [comment]
That's just fine learning and practice is what this is all about. check out the instructions on the [contributing](https://github.com/TheDevPath/googleMaps-offline-navigator/blob/development/CONTRIBUTING.md#how-to-contribute) doc to get your repo and branch set up and the instructions on the readme to get things installed to run the app. Feel free to reach out if you need help getting going.
thanks!
