### ISSUE TITLE
Build a Places component

### ISSUE THREAD

**Issue by motosharpley** [TheDevPath/googleMaps-offline-navigator#118]
Build a component to utilize the google places api.
You can check the search component for reference to help you along.
consider this the landing point for this component the will use the users geolocation to per-populate a nearby search when opened.
see - https://developers.google.com/maps/documentation/javascript/places#place_search_requests
for more details on the api

**Comment by sameerkhan116** [comment]
This can be closed now I guess. I'll add the other issues separately.
