### ISSUE TITLE
Story Board

### ISSUE THREAD

**Issue by motosharpley** [TheDevPath/googleMaps-offline-navigator#12]
Create a project story board to visually represent user interaction and use case flows. Utilize the projects wire frames to illustrate users paths of interaction through the app to identify either smooth flow or bottleneck issues. The goal here is intuitive interaction flow.

**Comment by motosharpley** [comment]
cool I think it makes sense for this to go with your wire frames. I usually end up doing it in visio, though not out of preference just out of it's what I have. So again I say Builders choice.

**Comment by pjdmatts** [comment]
Let me know if this is the sort of thing we are looking for.

[storyBoard.pdf](https://github.com/TheDevPath/googleMaps-offline-navigator/files/1650636/storyBoard.pdf)

**Comment by motosharpley** [comment]
Let's post these and the wireframes on the team discussion board as well. I'm sure we will iterate over them many times as we go along but I think it's looking great so far! And should definitely help everyone get a better picture of where we are headed.

**Comment by motosharpley** [comment]
Closing this issue continue discussions on team discussion boards
