### ISSUE TITLE
Refactor the Search AutoComplete code to use google-maps-react packages instead of manipulating the DOM (as is being done right now)

### ISSUE THREAD

**Issue by sameerkhan116** [TheDevPath/googleMaps-offline-navigator#122]
Do you want to request a feature or report a bug?
Enhancement

If this is a feature request, what is motivation or use case for changing the behavior?

If the current behavior is a bug, please provide the steps to reproduce.

What is the expected behavior?

What is the current behavior?
At present, the search autocomplete code creates a script on the DOM and then runs the script. However, in React, you should not touch the actual DOM and only manipulate the Virtual DOM so we need to refactor the current code.

Please mention other relevant information.

    Node version
    npm version
    Operating system
    CLI version
    Browser
    Device

**Comment by motosharpley** [comment]
I missed it in the recent PR so we need to refactor the default hard coded autocomplete latlng to be dynamic based on users geolocation rather than hard coded

**Comment by motosharpley** [comment]
yes but the autocomplete now has preference to Australia so for example before if I started to type the name of the city i'm in or one nearby the autocomplete suggestions were more relevant.  Now it suggests places in Australia instead. Those coordinates are used to influence the way the autocomplete makes suggestions, so in the context of navigation the user is most likely to be searching for something nearby therefore using the current location will provide more relevant autocomplete suggestions. 
Now if we were using this for an Australian tourism app the current coordinate preference would be ideal.

**Comment by sameerkhan116** [comment]
Oh okay, I didn't realize that. Also, are we limiting the autocomplete to cities or can it autocomplete to anything?

**Comment by motosharpley** [comment]
no I think we can open it up since we have places now, I'm not sure off hand what all categories are available but I think it would be good expand it a little.
