### ISSUE TITLE
refactor client proxy config

### ISSUE THREAD

**Issue by motosharpley** [TheDevPath/googleMaps-offline-navigator#124]
refactor the client proxy config - correct the /api usage no longer on back end.

**Comment by seckboy** [comment]
If this is just deleting the following from preact.config.js then I can do this:

		config.devServer.proxy = [
			{
				path: '/api/**',
				target: 'http://localhost:8081'
			}
		];

**Comment by motosharpley** [comment]
ya just include it with the PR when you do the signin connection
