### ISSUE TITLE
App home page/route

### ISSUE THREAD

**Issue by motosharpley** [TheDevPath/googleMaps-offline-navigator#126]
Populate the client home route with summary of app and navigation to main app features 

get Idea how we are using this page...
for a tutorial on this look to section 3 of this [Udacity course](https://www.udacity.com/course/intro-to-progressive-web-apps--ud811)

**Comment by redragonx** [comment]
Can you assign me to this please?

**Comment by jkwening** [comment]
@motosharpley @redragonx what is left for this? Currently we have a home screen. We still need a splash screen I believe. Is that all or am I missing something? If so, we should probably close this ticket a create a more specific issue for what remains. Thanks.

**Comment by redragonx** [comment]
Sorry for the late reply, but I had unexpected real life problems popped up. That's why there was no response.
