### ISSUE TITLE
Create a contributor doc

### ISSUE THREAD

**Issue by motosharpley** [TheDevPath/googleMaps-offline-navigator#127]
Create a CONTRIBUTORS.MD doc to say thank you and give credit to contributors for their generosity and hard work.

**Comment by sonalikatara** [comment]
@motosharpley  I would be happy to work on creating this doc. This will be my first contribution.

**Comment by motosharpley** [comment]
@sonalikatara please submit pull request on this issue to docs-dev branch.
Thanks!
