### ISSUE TITLE
Customize the web app manifest file

### ISSUE THREAD

**Issue by motosharpley** [TheDevPath/googleMaps-offline-navigator#128]
See [here](https://developers.google.com/web/fundamentals/web-app-manifest/) for info on the purpose of the app manifest file.
Customize the existing manifest file to reflect the specific needs of the navi app

for a tutorial on this look to section 3 of this [Udacity course](https://www.udacity.com/course/intro-to-progressive-web-apps--ud811)

**Comment by alicepalazzolo** [comment]
@tanyagupta where would you like me to place the additional app icon files ? The same folder as before?

**Comment by motosharpley** [comment]
@alicepalazzolo same folder is good also can you load the logo on a transparent background at the same time please 😃 and Thank you!

**Comment by alicepalazzolo** [comment]
@tanyagupta what size would you like the logo?

**Comment by motosharpley** [comment]
@alicepalazzolo we are currently just using it for the splash/ home screen which will only display logo, maybe a tagline and two large buttons leading to map & profile.

**Comment by alicepalazzolo** [comment]
This Pull I just added should have everything you need @tanyagupta I also added  fav icon package which also has a manifest file and set ups for safari, apple and microsoft app icons, if you want to use this let me know and i can give you instructions for html5, nod CLI or Google Web STarter Kit

**Comment by tanyagupta** [comment]
Thanks a lot! Bryan hold off on merge please. I will add these and update the pr
