### ISSUE TITLE
Mock-ups

### ISSUE THREAD

**Issue by motosharpley** [TheDevPath/googleMaps-offline-navigator#13]
reference wire frames and story board to create rich graphical mock ups of the various app views.

**Comment by motosharpley** [comment]
please be sure to coordinate with @pjdmatts on this task.
Thanks!

**Comment by jp853** [comment]
Sure thing. I’ll be home Monday evening to get started.

**Comment by jp853** [comment]
Just got home. Reviewing the storyboard and wireframes @pjdmatts designed as well as the color schemes then getting started.

**Comment by motosharpley** [comment]
Closing this issue for now. We can continue to review via team discussion boards
