### ISSUE TITLE
refactor / enhance places component

### ISSUE THREAD

**Issue by motosharpley** [TheDevPath/googleMaps-offline-navigator#132]
-    Improve InfoWindow -> clicking on a marker should give more information on the place.
-    Moving the marker on the map around should give search results around that place, at the present, maps API gets current location and uses that as center to give places nearby.
~~List of places is generated only after clicking once on the map~~
   ` <Map google={this.props.google} center={{lat: this.state.lat, lng: this.state.lng}} onClick={this.fetchPlaces} >`

~~because of this onClick handler. Other logical method was onReady but the this.state.lat and lng are not available when the Map is ready so need to figure out a work around for that.~~

**Comment by khusbuchandra** [comment]
@motosharpley , apart from name & address what other details should be displayed? Also do we plan to customize marker or we go with default one.

**Comment by motosharpley** [comment]
@khusbuchandra  I'm not sure exactly what all the options are but I think phone and website would be good if they are available. We can use the default for now and make a custom one if time premits.

**Comment by jkwening** [comment]
sorry somehow missed this convo chain, else I would've pushed parts of my commits earlier. @khusbuchandra please see PR #169. We've moved to leaflet for map rendering and OSM for tiles. The maps route is where you need to incorporate the places features. It is now built out for that step, taking the query results, updating the map correctly with specific marker based on user's selection and if a place a valid place, get the details for the places and present to the user.

If you feel comfortable with the other remaining tasks I think I needed for map view component as whole I can hand that ticket for you to continue and I can transition to building out the directions feature. Thanks and sorry for the inconvenience.

**Comment by khusbuchandra** [comment]
@jkwening  I wasn't aware of this and even i raised a PR [#171](https://github.com/TheDevPath/googleMaps-offline-navigator/pull/171) sometime back. In that case those changes won't be needed and this issue would be also invalid.

**Comment by jkwening** [comment]
@khusbuchandra apologies about that...there's a lot of moving parts and it took me longer than I intended to transition us from google maps to open source based renderer and tiles. If possible, please turn your attention to #145 this view will include the places features you were working on; I'll assign that ticket to you. I'v merged in PR #171 and it also has notes about other remaining tasks that need to be completed if you need ideas of what features to expand further. Please incorporate the related places features in this ticket that are missing into that route's view.

Note: the search query result also includes google place_id if a place is returned as result; so you can easily make a backend server request to get the details for that place.  There's a server endpoint for that if passed a valid google place_id value.

Again sorry for the confusion and inconvenience. I appreciate the work you put into #171 but want to avoid further redundancies as we move toward the MVP. Thanks!

**Comment by motosharpley** [comment]
@khusbuchandra Sorry about this I missed the fact that we had this as an issue from the last revisions and did not get it synced up with the new map view. 
I guess we can just chalk it up to an educational exercise learning how to deal with issues you encounter in workplace projects. 🤣 or something

**Comment by khusbuchandra** [comment]
@jkwening, I understand you, no more apologies :) . This does happen and anything for the betterment of the MVP. My intentions are all about learning and this would fall into that. I would check out the relevant issue and PR you have mentioned and see  if I can get a grasp of it and provide contributions.
@motosharpley , exercise done and noted 💯  :)
