### ISSUE TITLE
Build Saved Pins component

### ISSUE THREAD

**Issue by motosharpley** [TheDevPath/googleMaps-offline-navigator#139]
Build out the savedPins component on the client app and connect it to the savedPins api resource to save to DB.

**Comment by sameerkhan116** [comment]
Hey Bryan, just wanted to know how this component will be different than the favorites one? 
Also, in my opinion the best way to do this would be - when marking a place as saved, add it to a saved places state and then pass this state as props to the Saved Pins Component. Just a suggestion if someone is looking to implement this.
I'd love to work on this but I've got a really busy week ahead.

**Comment by motosharpley** [comment]
Hey Sam thanks for asking,  I'm going to also add an issue to refactor the favorites component to take in saved pins, places, and directions components. The favorites component will basically build the arrays and control how they are displayed using the data from the pins, places and directions components. The focus of the pins component should be handling saving and retrieving the data via state and props as you said as well as making sure we are saving to the database for persisted data on the api side of things.

**Comment by jkwening** [comment]
closing in favor of #185 - eventually we probably want implement a better ui for this but what we currently have implemented works for now.
