### ISSUE TITLE
Outline of project features

### ISSUE THREAD

**Issue by jkwening** [TheDevPath/googleMaps-offline-navigator#16]
Creating this ticket to track the proposed project features that is currently in the ReadMe.md so we can continue to discuss and breakout into modular pieces as it evolves.

## Features

* The interface will **display a map** of a designated area

* **Users** will be able to:  
    * Search for a location
        * By typing into a search field
    * View most recent and frequent search
    * Drop a pin at a location
        * By placing a pin on the map
        * By clicking 'drop pin' next to search results
    * Get directions to a selected location from:
        * Their current location
        * Another dropped pin
    * Save a dropped pin
    * Save a set of directions
    * View list of dropped pins ('saved places')
    * View list of directions ('saved directions')

* **The app** will:
    * Use the Google Maps API to:
        * Display the map
        * Provide a search interface
        * Provide a current location
        * Provide directions
    * Interface with a database to save a users:
        * Saved places
        * Saved directions
    * Maintain last state on loss of signal including:
        * Current map View
        * Saved places
        * Saved directions

**Comment by jkwening** [comment]
Do we want to include search history feature? Something like last 10 searched location and/or dropped pin locations - independent of whether they're saved or not.

**Comment by motosharpley** [comment]
Ya I think it might be a good idea to have most recent and maybe most frequent as well.

**Comment by jkwening** [comment]
Closing in favor of tracking with road map.
