### ISSUE TITLE
Preload saved pins on map

### ISSUE THREAD

**Issue by jkwening** [TheDevPath/googleMaps-offline-navigator#183]
Preload saved pins on map view with unique marker/pin icon (maybe a star or heart, can be simply a yellow marker for now to differentiate from normal dropped pin). See [leaflet tutorial](http://leafletjs.com/examples/layers-control/) on layer groups.

Next issue:
- limit this to only when user has been authenticated or if not logged in saved during "guest" mode

**Comment by shiolovesgod** [comment]
Hey @jkwening I think I'd like to take a shot at his issue, just to clarify:

* A user's places are saved in the db
* I need to load those places with a different markerwhen the map is loaded

**Comment by motosharpley** [comment]
I have also reached out to alice to see if we can make a custom navi icon marker. 
@shiolovesgod yes pins are saved to the db and a limited number could also be cached by the service worker. 
and yes the saved place should be loaded with a different marker

**Comment by shiolovesgod** [comment]
Are we planning to cache the pins based on date created or frequency of use? 

Either way, for now I plan to cache based on the order returned in the request from the frontend.

Whatever we decide should be returned by the GET request from the frontend...

**Comment by motosharpley** [comment]
an index for frequently used would probably be nice but to start we can also just keep things simple

**Comment by jkwening** [comment]
completed in PR #208
