### ISSUE TITLE
style profile route

### ISSUE THREAD

**Issue by motosharpley** [TheDevPath/googleMaps-offline-navigator#184]
style the profile route and the related components
Add styling to nav - buttons

- [x] ProfileCard  add styled containers for users saved pins & recent search history

- [x] settings - route

- [x] signout - route

**Comment by trickling** [comment]
I will work on this.

**Comment by motosharpley** [comment]
@trickling I have sent you an invite to the github team once accepted I can assign this issue to you.

**Comment by motosharpley** [comment]
@trickling maybe you could start with login or register they are ready to go and have specific issues created #206 and #205 These are the entry point to the profile rout at this stage.
