### ISSUE TITLE
User location control button for map view

### ISSUE THREAD

**Issue by jkwening** [TheDevPath/googleMaps-offline-navigator#190]
Currently there's no easy way recenter the map view back to the users current location. Add a "user location" control component to the map view overlay that on click sets the map view back to the user's location.

Suggested location: right side, about 1/3 away from the bottom of page or right above the attribution section of the map (bottom right).

Note: you will need to set `z-index`=1000 for React component to overlay on top of the leaflet map container.

**Comment by sameerkhan116** [comment]
Hey I'd like to give this a shot.
