### ISSUE TITLE
Updated mock ups for NAVI

### ISSUE THREAD

**Issue by motosharpley** [TheDevPath/googleMaps-offline-navigator#195]
New ui mock ups to reflect NAVI and matching color shceme.

**Comment by alicepalazzolo** [comment]
New UI Click through can be viewed here: https://xd.adobe.com/view/5e55d994-c6ba-4a3f-b1b9-3f9a8a65f072 (you can click on certain elements in the page and see where they lead). Not everything is complete yet but a few screens for the look and feel. I have also added a quick screenshot of everything.
![mockup_quickview](https://user-images.githubusercontent.com/35308564/36930291-ba1afcce-1e6b-11e8-9ece-d86a227a83d5.PNG)

If anyone wants to view design specs they can be found here: 
https://xd.adobe.com/spec/023c1fff-14f3-4062-b461-5cb725bc539d/# 
(You will need to create a free adobe account to view)

**Comment by motosharpley** [comment]
@TheDevPath/grow-with-google Check out the latest UI mock ups

**Comment by jkwening** [comment]
Thanks @alicepalazzolo Now that looks pretty...if we can get the user location icon and pin icons created we can load this into existing code this weekend.

**Comment by khusbuchandra** [comment]
Good job @alicepalazzolo , I really like it.

**Comment by tanyagupta** [comment]
Very nice!

**Comment by alicepalazzolo** [comment]
@jkwening where would you like them? I have made them in multiple sizes for different devices if needed or I have also exported them as SVG's depending on what you want to use. SVG's are great for resizing and quicker load times.

**Comment by jkwening** [comment]
@alicepalazzolo you can place them in the `~/client/src/assets/icons` folder and submit a pull request. Feel to add subfolders as needed if there's a natural way to organize them. Thanks!

**Comment by jkwening** [comment]
@alicepalazzolo actually can you add the user location and pin icons into the leaftlet subfolder under icons? Just remembered that is where the default map icons are stored. Also, I think we want PNG since SVGs are not supported by all browsers yet. Thanks.

**Comment by alicepalazzolo** [comment]
I have added these to the solution, let me know if you have any questions or need anything else. I added image sizes for Adding in icons for sizes: ldpi, mdpi, hdpi, xhdpi, xxhdpi, and xxhdpi for the following icons

- Change Direction
- Current Location
- Destination Pin
- Find Location PIn
- FoundLocationSpot
- Get Directions
- Navigation Menu Icon
- Profile Icon

Also includes dark & light logo

**Comment by jose8a** [comment]
@jkwening SVG support is actually universal (or as universal as it gets).  According to caniuse website, it is at 97.92%.  I would argue using SVG wherever possible nowadays instead of sending a bunch of extra files.  This way you only need one per icon, or one in total if you use a sprite-sheet.

https://caniuse.com/#feat=svg

**Comment by alicepalazzolo** [comment]
@jose8a I thought that was the case. I can easily upload the SVGs also if you would like

**Comment by jkwening** [comment]
@jose8a looks like I'm wrong, I swear I read somewhere that safari mobile still had issues with SVG. Since that's not the case, yes, I agree SVG is the better choice.

@alicepalazzolo can you please upload SVG version?

Thanks!

**Comment by alicepalazzolo** [comment]
@jkwening They have been added. Let me know if you need anything else.

**Comment by jkwening** [comment]
@alicepalazzolo can you point me to paths for nav bar background image and splash screen background image? I couldn't find them in the assets page. Thanks!

**Comment by alicepalazzolo** [comment]
@jkwening hey those were not added as people were asking for location and pin icons. 

Also would the nav bar just be a background gradient with css ? I can give you the css for it if you want if not I can make svg as well.(generally I only background images for header when doing an actual application as there are limitations, however this is a web app and can handle css)

As for the background on the splash screen and main page, I assume this would use the same background image ( of the map) with a background color over it ( or gradient of splash screen) controlled by css.


I think keeping these items controlled by css allows for quick theme changes for the look and feel to be handled with css. Let me know what you think.

**Comment by jkwening** [comment]
@alicepalazzolo thanks for the clarification. Sorry if you posted somewhere else, yes, can you please provide the css color you're using in mockup? I was looking at it for bit thinking how to implement it and color gradients didn't come to mind; thanks for the re-introduction to gradients!

**Comment by gayakrish** [comment]
I just implemented the top navbar (css gradient) with the NaviHomeIcon and ProfileIcon while working on "CSS Styling Components #108". I am yet to check in though.

**Comment by jkwening** [comment]
@gayakrish wonderful. I've assigned #207 to you, which is specific for the navbar. Can you commit and request a PR for that issue when ready? Thanks.
