### ISSUE TITLE
Create Nav component per mockup

### ISSUE THREAD

**Issue by jkwening** [TheDevPath/googleMaps-offline-navigator#207]
- we have updated mockups that you can reference:
  - [overview](https://user-images.githubusercontent.com/35308564/36930291-ba1afcce-1e6b-11e8-9ece-d86a227a83d5.PNG)
  - [interactive](https://xd.adobe.com/view/5e55d994-c6ba-4a3f-b1b9-3f9a8a65f072/screen/a10637c7-7aae-4cfa-ab2c-4ad46bf153a2/Homescreen/)
  - the related icon images can be found in the `~/client/src/assets` subfolders
    - references `logos` and `/icons/leaflet/*` subfolders

**Comment by gayakrish** [comment]
Looks like the navbar is already implemented before I could check in mine. Is there any other change that needs to be done as part of this issue?

**Comment by jkwening** [comment]
@gayakrish not for this issue - its squared away now. Please see the new issues section of PR #216. There are related tasks that need to be implemented. Let me know if any peaks your interest.

**Comment by alicepalazzolo** [comment]
@jkwening I know this was closed but the colors were off for the navbar- also it didn't have browser compatibility gradients in it. Can I implement an update?
