### ISSUE TITLE
Pins cover map as you click around (even if you don't save the pins)

### ISSUE THREAD

**Issue by steveone** [TheDevPath/googleMaps-offline-navigator#226]
This is a bug found in in the Enhance saved pin feature - Issue #204

If you click on multiple points of the map, each location will get a pin without you hitting "save" on the pins. The expected behavior is that one pin will be created, and if you don't hit "save" the pin will be removed when you click elsewhere on the map.

See attached screenshot for visual (taken in Chrome on a mac)

<img width="473" alt="screen shot 2018-03-11 at 9 34 41 pm" src="https://user-images.githubusercontent.com/13615356/37265952-19a7a19c-2574-11e8-8b19-3de089612fd6.png">

**Comment by jkwening** [comment]
@steveone want to take a crack at fixing this? If so, I'll assign the ticket to you.

The code logic is in `~/client/src/components/LeafletOSMMap/index.js`.  We're using [Leaflet](http://leafletjs.com/index.html) module for rendering maps.

**Comment by steveone** [comment]
@jkwening I'd be happy to take a crack and resolving this issue. Thanks for pointing out where the code is. I will take a look at it shortly.

**Comment by jkwening** [comment]
resolved in PR #244
