### ISSUE TITLE
Add helmet package for security

### ISSUE THREAD

**Issue by scottwestover** [TheDevPath/googleMaps-offline-navigator#32]
Do you want to request a feature or report a bug? - Feature request

If this is a feature request, what is motivation or use case for changing the behavior? - Adding the helmet package will help make the express app more secure, and it helps the app follow the best security practices (https://expressjs.com/en/advanced/best-practice-security.html).

**Comment by CodeDraken** [comment]
[pull request 33 - Added helmet to help with express security ](https://github.com/TheDevPath/googleMaps-offline-navigator/pull/33) looks good :+1:
