### ISSUE TITLE
Set up Unit testing

### ISSUE THREAD

**Issue by motosharpley** [TheDevPath/googleMaps-offline-navigator#36]
Initial set up to facilitate unit testing suite.

**Comment by tophergates** [comment]
Personally, I do not have much experience with testing suites. If anyone has more experience with this, what are your thoughts/suggestions on a which testing library to use? I assume we'll need separate testing suites for server vs. client side...

**Comment by CodeDraken** [comment]
@tophergates 

Well, I don't know about Preact, ( maybe enzyme works with it? ) but on the server Mocha, Expect, Supertest, and Superagent is nice and easy to setup. ( I haven't actually contributed yet just throwing some ideas out there )

`yarn add --dev mocha expect supertest superagent`

**Comment by motosharpley** [comment]
Ya I have written tests in ruby mostly. For javascript the only thing I've used is mocha and chai and not extensively by any means. I will have to look but I think I might have a sandbox project I was messing with a while back to get familiar with mocha/chai. They seem to be common or jest would be another option to consider.

**Comment by motosharpley** [comment]
so here's chai for preact https://github.com/developit/preact-jsx-chai/
