### ISSUE TITLE
Implement routes for getting, saving, and updating saved pins

### ISSUE THREAD

**Issue by jkwening** [TheDevPath/googleMaps-offline-navigator#57]
Complete routing for saved pins feature for the app. Currently the plan is to handle routes for this as part of the search feature so routing url endpoints should go into: ./routes/search.js module.

Overview of task:

- [x] define getting, saving, updating, and deleting end points in ./routes/search.js for dropped pins
    - [x] get route
    - [x] post route
    - [x] delete all pins route
    - [x] delete given pin given db id
- [x] implement controller functions for end points in ./controllers/saved-pins-controller.js

Notes - initial model for storing dropped pins data is in ./models/saved-pins.js; should consider adding a description/user defined label feature for dropped pins.

**Comment by mallek** [comment]
I am working on adding in routes following the pattern laid out in the map routes and google-api-controller.  I have already submitted a PR that precedes this. once merged I can PR this.
