### ISSUE TITLE
App Wiki

### ISSUE THREAD

**Issue by motosharpley** [TheDevPath/googleMaps-offline-navigator#6]
Build out app wiki home page

**Comment by seckboy** [comment]
This is the only item I see in the backlog. Do you still want a wiki? I found a site to host a wiki for free. 

http://udacitygooglemaps123.wikia.com/

I restricted permissions so you should not be able to edit it unless you create an account and tell me your username. Is this what you had in mind? If so, do you assign the issue to me?

**Comment by motosharpley** [comment]
The functionality to build out the wiki is right on github, no need to use
the outside source. Yes if you would like to work on this I can assign the
issue to you. Anything that is not already assigned to someone is available
not just the issues tagged with backlog. I will also be adding a lot of new
issues this week to continue our progress so there is still lots's to do
even though not that many issues are currently posted.

You can also reach out to me if you want help finding tasks that you are
interested in there may be things that I just have not yet gotten around to
adding issue tickets for yet,

thanks,

Bryan

**Comment by Koko-Dev** [comment]
Working on a basic digital drawing to Map the interaction between frontend, backend, and Google Maps API.  Will go over forum and Github discussion today.

**Comment by pjdmatts** [comment]
@Koko-Dev, awesome. Please can you reach out to @bree on Slack (I did not see them in the team yet) - we were working on some notes for the Wiki content/structure yesterday and this may provide a shortcut since some of notes were lifted from the Saturday meeting on Slack. We actually left a place-holder for such a diagram, so great minds think alike...

**Comment by pjdmatts** [comment]
See this is why we don't use our super hero identities :)

**Comment by pjdmatts** [comment]
Hi @motosharpley - please can you @Koko-Dev and I edit access on the wiki?

**Comment by Koko-Dev** [comment]
I forked the project onto my Koko-Dev and have the first bit of it done.  Left you a message @motosharpley on how best to upload images.  Am working on a few more ideas for images.  In my research, I saw that one could acquire a place to upload the image which would give us a URL.  One could also create another file for Wiki Images, as I am certain there will be quite a few and it may be good to keep them separate from the site images.  Or, if there will not be many images on the site, one could simply put them there.  It's been loads of fun so far!  

@pigmatts  Ha!  Funny you should mention superhero identities.. That is exactly what I do, write superhero stories for childrens' superhero alter egos.  Must have seeped over to webdev.  :)  

And, last, I may need a bit of guidance on pushing all the changes to the main origin master thingy.  It will be my first commit!  Very exciting.  Or first push...  Going through an alternate git course, presently.. I am sure I will get it straight.  :D
