### ISSUE TITLE
Set up Client Component Skeleton

### ISSUE THREAD

**Issue by motosharpley** [TheDevPath/googleMaps-offline-navigator#68]
Refer to Project Roadmap and build component file structure with basic 'hello world' components

**Comment by pjdmatts** [comment]
Assume this means client app components identified in the MVP, and this is for the attention of the @TheDevPath/front-end-dev-team ?

**Comment by sperrye** [comment]
Is there a wireframe or a list?

**Comment by motosharpley** [comment]
please see https://github.com/orgs/TheDevPath/teams/front-end-dev-team/discussions/1
