### ISSUE TITLE
Client Side Routes

### ISSUE THREAD

**Issue by motosharpley** [TheDevPath/googleMaps-offline-navigator#69]
Set up Client Side Routes for app skeleton

**Comment by seckboy** [comment]
I can start on this. I'm picturing setting up some placeholders for both routes and components. The components can be replaced with the real components people are working on. I actually played around with something like this over the weekend. I created a signin page with a button that takes you to a map page no matter what you enter into the form and links to "register" and "forgot password?" that take you to forms with buttons which again will take you to a map page no matter what you enter. I also created different placeholder headers for map vs non-map views. Does this sound like what we want to start?

**Comment by motosharpley** [comment]
I think it sounds like you've got the right idea. I will go ahead and assign this to you and we can always just make adjustments on the PR as needed.
Have fun!
