### ISSUE TITLE
app landing page

### ISSUE THREAD

**Issue by motosharpley** [TheDevPath/googleMaps-offline-navigator#7]
Build a landing page for welcoming new users to the app.

**Comment by pjdmatts** [comment]
I would like to take a swing at this - though probably should wait for mock ups? 
Also not at all sure how this fits in with Preact.js, but happy to build something with hmtl and css while I am reading the docs on everything else you guys are doing...

**Comment by pjdmatts** [comment]
It _looks like_ I would make a new folder under /client/src/routes/home/, and write an index.js that returns the html that we want? Let me know if I am heading in the right direction.

**Comment by motosharpley** [comment]
Sounds like a plan!  I think your logic sounds good on setting up index.js although to be honest I really haven't had a chance to dig into preact much beyond loading things up to test that we aren't breaking anything with pull requests. So play around with it, if you hit a snag let me know I'll help figure it out. It should be quite similar to react.

**Comment by pjdmatts** [comment]
This has taken longer than I would like. I have made a static version [here](https://github.com/pjdmatts/static-mapE) and have a fork on my local machine with most of this working within the preact app - One snag is getting the landing page to show up on its own without the header from the preact app, the other is learning jsx on the fly. Text and stying I am fine on but I need to look into images. 
If this (the landing page) becomes a bottleneck let me know.

**Comment by motosharpley** [comment]
No rush here we can work on this at any time. It will pretty much be a separate asset from the main app in a sense. If this were a native mobile app think of this as the page to come download the app, we will provide some crafty little tricks to make our pwa behave in a similar manner. So that the user can still have the icon to launch the app we just handle it a bit differently behind the scenes.
To resolve without the header we will have to do some work on the routes and all the boilerplate stuff will be going away shortly as we start building out our components anyways.
