### ISSUE TITLE
Create an Icon pack

### ISSUE THREAD

**Issue by motosharpley** [TheDevPath/googleMaps-offline-navigator#72]
Create a pack of Map-e png icons with transparent background matching the sizes of the preact Icon files in the client>assets>icons folder
These are used for things like favicon, home screen Icon on mobile devices etc

**Comment by redragonx** [comment]
Do we have colors/branding picked out?

**Comment by motosharpley** [comment]
there are two example color schemes in the repo but nothing is set in stone multiple choice is always nice especially with a group this big

**Comment by redragonx** [comment]
Alright i will think about it, but for now, i will focus on the components.

**Comment by pjdmatts** [comment]
Does the logo discussion go along with this?
Any designers out there who want to assist?
@TheDevPath/ui-ux-design-team

**Comment by redragonx** [comment]
I will help out with the logo design here.

**Comment by motosharpley** [comment]
Here is a thread on the discussion board we had been putting ideas on https://github.com/orgs/TheDevPath/teams/grow-with-google/discussions/7
