### ISSUE TITLE
Refactor and complete apiRoutes.js in tests

### ISSUE THREAD

**Issue by jkwening** [TheDevPath/googleMaps-offline-navigator#75]
This was the file used to configure our backend tests folder and skeleton. It's incomplete and needs refactoring.

1. Rename file to users-test.js (`git mv tests/apiRoute.js tests/users-test.js` - assuming you're pwd is the root "GOOGLEMAPS-OFFLINE..." folder).
2. Refactor code to test the endpoints in routes/users.js and its respective controller functions (controllers/users-controller.js)

**Comment by jkwening** [comment]
#1 above has been completed in PR #99 but still need to complete #2 above - doesn't include cases for all user end points.

**Comment by desdemonhu** [comment]
Started working on the users routes

**Comment by desdemonhu** [comment]
@mallek I was running tests just fine the other day, then I pulled down changes from development branch a few minutes ago, and now I get this error any time I try to run the server tests 
```Server is running at http://localhost:8081
  1) "before each" hook: populateUsers for "test runner should work"

  0 passing (2s)
  1 failing

  1) "before each" hook: populateUsers for "test runner should work":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```
if I remove the beforeEach with populateUsers, the tests run, just some of them obviously fail. Looking at your seed I can't figure out what is wrong or even what changed. I tried doing a hard reset of my branch and that didn't help. Do you have any suggestions on what I could try?

Thanks!
