### ISSUE TITLE
App logo

### ISSUE THREAD

**Issue by motosharpley** [TheDevPath/googleMaps-offline-navigator#8]
Create a logo that can be used universally throughout the app and as the Icon. 

This can also coincide with issue #72 Create an Icon Pack

Logo Concept
The goal is to create a representative character for the smart mapping app. We want to convey a helpful personality that is playful and adventurous. You can work with the name Map-e, Mappy or propose something new, just keep in mind it should be as short as possible and be reasonably perceived as a character/personality. Think of things like siri, alexa, and the android robot etc for inspiration as to the strategy here. Map-e should be your reliable little pocket size guide to find new things and navigate the way to get you there, Even when signal is spotty.

Requirements – Constraints
    • logo must be distinguishable down to 16px x 16px
    • Should scale cleanly
    • should work both monotone and full color
    • should be usable for the complete icon pack in all sizes

**Comment by pjdmatts** [comment]
I know there was some discussion on the team boards, but has a logo been selected?
@TheDevPath/ui-ux-design-team

**Comment by motosharpley** [comment]
It's still open game to anyone feeling artistic!

**Comment by desdemonhu** [comment]
Yes please help! I’m bad at this :D

**Comment by alicepalazzolo** [comment]
![navi-icon](https://user-images.githubusercontent.com/35308564/36318402-bfc053a4-130d-11e8-9378-f6532905120c.PNG)
![navi](https://user-images.githubusercontent.com/35308564/36318407-c20422b2-130d-11e8-928f-970ca61a097f.PNG)
So I am going to be working on the Logo & Icon. I was thinking of doing something called NAVI. This gives us the short iconic style name like Siri & Alexa. It also references the sidekick/ companion of Link in the Legend of Zelda. Also Navi is short for Navigation, which is what we are doing for the user!

**Comment by redragonx** [comment]
Looks great so far!

**Comment by tanyagupta** [comment]
Hi guys, I am working on Issue #128  and for that I was wondering if we could get more sizes for the logo? 
The Web Manifest Section in the Intro to PWA course materials recommend the following sizes: 48,96,128,144,192,256,384,512. We have 192,512,182,16,32,150. 
Ideally we would also have 48,96,128,144,256,384
![icons](https://user-images.githubusercontent.com/8497274/36914333-ebe1d544-1e1a-11e8-87d2-28dd7093820e.png)
