### ISSUE TITLE
Map component

### ISSUE THREAD

**Issue by pjdmatts** [TheDevPath/googleMaps-offline-navigator#81]
The first phase of this task is complete but needs to be refined with some CSS clean up and connecting to our back end bridge rather than direct to the google API when that functionality is ready.

Feature Request.

Please create a Preact component that shows a Map (using Google Maps API)

@seckboy and I are working on this

**Comment by seckboy** [comment]
On the google-maps-react-component branch at https://github.com/seckboy/googleMaps-offline-navigator I just took some code from this tutorial (http://blog.theodo.fr/2017/11/preact-progressive-web-app-webpack-material-design-web-apis/) and dropped it into a GoogleMap component. You need to put your own google maps api key into secrets.json for it to work. The url to see the map is /showMap. This is just a placeholder to show that the component can deliver a map. All the logic is in the component but I'm thinking the component would be simpler than this and it will just call the backend's "/api" routes to get what it needs. This has no service worker or caching or anything yet - it's just something to get us thinking about what the component should do.

**Comment by motosharpley** [comment]
I will pull a copy of this and go through it in more detail later tonight, but at a glance looks like your headed in the right direction to get our first prototype going.
Great job!
