### ISSUE TITLE
Profile component

### ISSUE THREAD

**Issue by pjdmatts** [TheDevPath/googleMaps-offline-navigator#84]
Feature Request

Please create a Preact Profile Component for the UI

@TheDevPath/front-end-dev-team

**Comment by pjdmatts** [comment]
@redragonx would like to work on this

**Comment by redragonx** [comment]
Profile features:
- See the following: name, username, email, password, and notification settings
- Edit everything above
- Delete account 
- See account creation time

Notification features:

- map updates
- app updates
- offline timer msgs (We should alert users a map is old or app is offline after a time)

**Comment by redragonx** [comment]
I will begin making the profile page this week.
