### ISSUE TITLE
Directions component

### ISSUE THREAD

**Issue by pjdmatts** [TheDevPath/googleMaps-offline-navigator#85]
Feature request.

Please create Preact Directions component

@TheDevPath/front-end-dev-team

**Comment by sperrye** [comment]
I'd like to start on this.

**Comment by motosharpley** [comment]
@sperrye To add to the question you had last night on the discussion board here is the API we will be working with on the server to then pass along data to this component. I Thought this might give you a better idea what you will have to work with https://developers.google.com/maps/documentation/directions/start

**Comment by jkwening** [comment]
@sperrye PR #101 includes the initial server side code that will be making calls to google api. Also, this link below specifics on rendering directions via google javascript api: https://google-developers.appspot.com/maps/documentation/javascript/directions#RenderingDirections

I'm currently returning the json without any modifications on the backend but I'm thinking of doing some additional processing to pull out the html directions to facilitate listing turn by turn directions. Let me know what you think.

**Comment by sperrye** [comment]
Thank you so much @motosharpley & @jkwening - can't wait to dig in!

**Comment by motosharpley** [comment]
I think this will end up being useful here https://github.com/googlemaps/google-maps-services-js

**Comment by jkwening** [comment]
@motosharpley I'm going to build a base view using [leaflet routing machine](http://www.liedman.net/leaflet-routing-machine/#about) as the shell from which we can then customize as needed. To begin with it will just start with your current location and allow you to add markers for start/to routing directions along with dragging markers to make changes.

Once this is up, I will create two/three new tickets:
1. Enhancing the view and expand capabilities including utilize passed start/end waypoints from map view to generate directions
2. (a) Figure out caching protocol for directions - I'm thinking prefetch and cache tiles at varying zoom levels traversing directions waypoint; then you can use user location to center directions map and thus pulling nearby tiles. We will need to figure out how to best handle off-course during offline mode.
2. (b) Finalize and implement handshake between front and backend to store and return saved directions

**Comment by jkwening** [comment]
closed for new specific issues.
