### ISSUE TITLE
Read me install instructions

### ISSUE THREAD

**Issue by motosharpley** [TheDevPath/googleMaps-offline-navigator#9]
Add Install instructions we need to provide detailed information on how to set up the front end app. ie. cd into client, then npm install and so on..

- dependency information

- add app status badges

**Comment by ricky-rose** [comment]
@motosharpley Is it ok if I add a table of contents to the main ReadMe.md file? That way once we start expanding the file with detailed information, it will be easier to browse, and editing the table of contents will also be easier if it is set up now instead of at the end.

**Comment by motosharpley** [comment]
@ricky-rose Yes absolutely that would be great!

**Comment by heggy231** [comment]
@motosharpley Bryan,
Within the README.md, Could I create a short video intro about what this project is about?
Here is resource on how to add to README.
https://stackoverflow.com/questions/4279611/how-to-embed-a-video-into-github-readme-md

First, I need to understand what this app is suppose to do.  Could we chat on Slack?

**Comment by motosharpley** [comment]
Yes @heggy231 that would be great. If you would like I can add you to the UI/UX Design team and you could reach out to the team members there to work on a prototype on invision.
