### ISSUE TITLE
fix client eslint config - missing plugins - Beginners Only Please!

### ISSUE THREAD

**Issue by motosharpley** [TheDevPath/googleMaps-offline-navigator#91]
Here is a hint to help you fix your first bug on an open source project. Look in the client directory at the eslintrc.json file. Compare this with the devDependencies in the client>package.json and add the eslint plugins to the to the eslintrc.json file.

Good luck!

**Comment by khusbuchandra** [comment]
I would like to take this up, it would help me initiate the process of figuring out configuration. But I am still struggling with the setup. I followed the instructions from Readme in client directory and getting errors. Need help to find what I am missing.

**Comment by jkwening** [comment]
@khusbuchandra what issues are you having? With git triangle workflow setup? If that is all good, the next step is to run npm install at:
1. the root of the project folder - for server node modules
2. cd into client and then run npm install - for preact node modules

After that you will need to setup a secrets.json file in config folder. Copy secrets-example.json. You can use the mongodb setup as is for now but will eventually need to get a google api key and update that section accordingly. Hope that helps. Feel free to ask specific questions.

**Comment by motosharpley** [comment]
@khusbuchandra you can also hit me up on slack and I can walk through things with you to get you started.

**Comment by khusbuchandra** [comment]
Thanks @jkwening  & @motosharpley , After few trial and errors, I figured it out. Will start contributing now.
